### ISSUE TITLE
Automatic Test Results Interpretation 

### ISSUE THREAD

**Issue by ereng** [ilabafrica/iBLIS#113]
Generate standard interpretations from standard test results
Later perhaps create another field for **comments** on results

**Comment by ereng** [comment]
@mapesa  done work on 1,2,4.
I think we should make 3 an issue of its own.
And merge this #124, 
What do you think?

**Comment by mapesa** [comment]
Okay. Merging.

**Comment by mapesa** [comment]
Back to you @ereng . Improvements in the handling of measures affects Prevalence Reports

**Comment by briankip** [comment]
This merge has broken results entry. Drop downs are not showing? Check!

**Comment by ereng** [comment]
All is well now...
