### ISSUE TITLE
Ungrouped test counts report

### ISSUE THREAD

**Issue by kitsao** [ilabafrica/iBLIS#134]
Test counts summary without test category grouping.

**Comment by ereng** [comment]
@kitsao perhaps it's better to have the functions **countPerStatus()**, **groupedSpecimenCount()** in the **specimen** model  (more logical) also **groupedTestCount()**, **testCountPerStatus()** in test

**Comment by kitsao** [comment]
@ereng , the functions are in the respective type models because types are of interest. As such, the counts are for the instances of the types. A 'test' can't exist without a 'test type', similar to 'specimen'.

**Comment by ereng** [comment]
That's true... hadn't seen it that way
