### ISSUE TITLE
Some form of search for lists

### ISSUE THREAD

**Issue by briankip** [ilabafrica/iBLIS#138]
We have long lists of Test types, specimen types e.t.c there needs to be a form of search on these pages with lists of these items. A simple search box that filters the items, preferably one that does not hit the DB.

**Comment by Piusyo** [comment]
@mapesa , I have been unable to find any other way to implement the `instant populate on type search feature` you requested without the use of data-tables which was previously implemented and dropped. Kindly advise on the way forward.
