### ISSUE TITLE
Migrating old data to new tables

### ISSUE THREAD

**Issue by briankip** [ilabafrica/iBLIS#148]
Creation of migration scripts to move the old data into the new tables.

* Ensure that you use scripts.
* Confirm that you are importing all data and that there are no warnings
* Counter-check to make sure all data matches.
* If current data is incorrect and you have to make changes, list them down in the scripts.

Tables needing migrations are [here](https://docs.google.com/a/strathmore.edu/document/d/18MaL6HXXYn5dJ5YJFL4r0O3iMi2emC7yTgL70x25qPY/edit)

**Comment by briankip** [comment]
Migration for patients tables https://gist.github.com/briankip/30b1f4c584d909eeeded

**Comment by ereng** [comment]
- The migrated passwords from old-blis don't work in new-blis
- Created a command 0efabd106bab703a0674f9257139d9dbd330690b for resetting all passwords to *password*

**Comment by ereng** [comment]
some measure_ranges are long, requires a change in the iblis.measure.measure_range.length to undo the truncation of data
from 60 to 200 characters
This is **stool for O/C**
