### ISSUE TITLE
ranges not imported

### ISSUE THREAD

**Issue by briankip** [ilabafrica/iBLIS#180]

**Comment by mapesa** [comment]
INSERT IGNORE INTO iblis.measure_ranges (measure_id, age_min, age_max, gender, range_lower, range_upper) SELECT r.measure_id, r.age_min, r.age_max, IF(r.sex='M',0,IF(r.sex='F',1,2)) AS gender, r.range_lower, r.range_upper FROM blis_301.measure m INNER JOIN blis_301.reference_range r ON m.measure_id = r.measure_id;
