### ISSUE TITLE
Saving results is taking too long.

### ISSUE THREAD

**Issue by briankip** [ilabafrica/iBLIS#189]
Try saving especially Full haemogram. Takes a long time, Sijui kama ni Curl that is slow or what.

**Comment by mapesa** [comment]
Followed the code but I can't simulate this here. 

Is the ip correct? the file name? the location? is the file readable?

Can you send me a copy of an actual celtac dump file (celtac.txt)?

**Comment by briankip** [comment]
Seems to be taking too long for curl to send the requests, need to disable the button and replace the "Save" message with Loading... so that people don't click it too many times.
