### ISSUE TITLE
Accept  reloads the page and forgets the search filter URGENT

### ISSUE THREAD

**Issue by briankip** [ilabafrica/iBLIS#208]
its confuding for the guys as it seems like the test has dissapeared and the filter is lost.  Especially when you search for a specific visit or patient.

**Comment by mapesa** [comment]
Boss! Which **Accept** is this?

The accept button on the tests log on the latest branch does not refresh the page and any filters are retained.

Did you mean some other button?

**Comment by briankip** [comment]
do this, search for a specific visit, then accept.

ALso when you have entered result and it redirects back the filter disapears

**Comment by mapesa** [comment]
I've seen the one for enter results. I'll work on this.

For the first issue, perhaps you mean 'Receive' and not 'Accept'

**Comment by briankip** [comment]
yes recieve sorry.

**Comment by mapesa** [comment]
I don't think retaining the filter after these changes will give you the effect you want if the `test-status` filter is set.

Checkout the `save-results-retain-filter` branch and try saving test results.

**Reason**: *Receiving** a test or *Entering Results* will change the status of the test from `not-received` to `pending` or from `started` to `completed`.

**Comment by briankip** [comment]
The test-status filter is not set, they just search for the visit-number

**Comment by briankip** [comment]
`save-results-retain-filter` has the search query in the search box after edit but the results are not filtered and also, the accept button still reloads and forgets the filter.

**Comment by mapesa** [comment]
I know. I'm working on this.

Pull latest commit for update.

What's pending it to redirect back to the same page in case what is being
edited was loaded from any page other than page one. I bet this is rarely
the case - we can fix that later when we have a little more time.

@brainkip, I've tested only for entering/editing results but it should also
work for receiving tests. Let me know if its good enough for your purposes.

**Comment by briankip** [comment]
The branch only has one commit

**Comment by mapesa** [comment]
Check again.
