### ISSUE TITLE
Show loader .gif when searching, and when sending, editing verifying results

### ISSUE THREAD

**Issue by briankip** [ilabafrica/iBLIS#209]
There is no user feedback to show that some action is on-going, especially for save results, users try saving multiple times.

**Comment by mapesa** [comment]
*Remember decoupling?* I think that would still be the neater solution in **iBLIS 2**.

Sending takes ages coz it has to wait for the remote communication to end. If the Sanitas box is down BLIS as well slow down.

**Comment by briankip** [comment]
Maybe we can find a way of doing it asynchronously, thus the UI does not lag.
