### ISSUE TITLE
Deleting measures that are tests

### ISSUE THREAD

**Issue by briankip** [ilabafrica/iBLIS#249]

**Comment by briankip** [comment]
script deleting measures that appear as tests. https://gist.github.com/briankip/939cfbee1a44a8488909
@ereng verify if this script does the trick.

**Comment by briankip** [comment]
138| Direct                         
142| Chloride                       
143| Potassium                      
144| Sodium                         
156| Epithelial cells               
158| ph                             
160| Spermatozoa                    
161| Bacteria                       
162| Red blood cells                
163| Yeast cells                    
164| T. vaginalis                   
166| Pus cells                      
169| Urobilinogen Phenlpyruvic acid 
171| Blood                          
172| Proteins                       
174| Glucose                        
181| WBC                            
184| HCT                            
185| MCV                            
186| MCH                            
187| MCHC                           
188| RDW                            
190| PCT                            
191| MPV                            
192| PDW                            
222| microscopic examination        
223| sperm count                    
224| motility                       
225| viscosity                      
226| volume                         
255| Indian ink                     
260| cell count                     
279| Water Analysis                 
281| Gram stain                     
282| Sub culture                    
307| Albumin                        
325| Pap Smear                      
328| Quality Assuarence             
330| Discordant Couples             
332| Tissue Impressions             
334| Breast                         
335| Ovarian Cyst                   
336| Fibroid

**Comment by ereng** [comment]
Confirming this is part of the list
171| Blood
336| Fibroids

**Comment by ereng** [comment]
Errors
 - syntax line 222 and 94
 - constraint testtype id=143 name=potassium is in use by tests id=68033

Otherwise it works
