### ISSUE TITLE
Receive button and save/edit/verify button taking too long

### ISSUE THREAD

**Issue by briankip** [ilabafrica/iBLIS#256]
I fixed the huge delays but its still taking too long as compared to the old blis, thus they are clicking like mad.

We need to move most of these crucial functionality to ajax, which is asyncronous. Then instead of going to the controller and doing more queries we just to a js window::back() and update the display accordingly. This will make the system a whole lot faster, and improve efficiency.

**Comment by mapesa** [comment]
I think what is needed is decoupling this process from the *send-to-sanitas
*code.

If we simply commit the results to the database instead of calling
*sanitasinterfacer* and waiting for a reply - these apparent delays should
be eliminated.

**Comment by kitsao** [comment]
To avoid the many clicks they do, we could somehow 'hide' the button. Displaying some message like 'Loading ...' in a modal window or even disabling the button once it is clicked might be possible options.

**Comment by briankip** [comment]
That's why am suggesting we do all these actions asynchronously, sending the results and waiting for the redirect take almost the same time. Even if we decouple the sending from the saving of results its, still take 0.9- 1.2 seconds to load the page.
