### ISSUE TITLE
Surveillance reports 

### ISSUE THREAD

**Issue by briankip** [ilabafrica/iBLIS#259]
Will gather more details from Joan and post here

**Comment by briankip** [comment]
TEST     |  < 5 years | > 5 years | Total
-------------|--------------|--------------|---------
Typhoid   |                |                  |             
Malaria    |                |                  |       
Dysentery * |               |                  |

- Typhoid data is derives from the number of salmonella antigens, plus the number of stool cultures with salmonella seen.
- Malaria data is derived from BS for MPS 
- Dysentery data is from the numbers isolated in stool for C/S

**Comment by briankip** [comment]
![img_20150213_123701](https://cloud.githubusercontent.com/assets/5111726/6225119/f42e2264-b696-11e4-835b-9f1142db9b6c.jpg)

**Comment by ereng** [comment]
- [ ] delete
- [ ] phpunit-test
- [ ] config authentication(js)
- [ ] side bar arrangement(create sub menu)
