### ISSUE TITLE
Migration KDH

### ISSUE THREAD

**Issue by ereng** [ilabafrica/iBLIS#286]
1. run `php artisan migrate`
1. run  [kap_migration_script.sql](https://github.com/ilabafrica/BLIS-Scripts/blob/master/scripts/kap_migration_script.sql)
1. run `php artisan migrate:results` (on branch kap-test-results) 
 - migrates results and resets passwords to password

**Comment by briankip** [comment]
password is not a good password, it was a terrible idea using that in Bungoma. change default to 123456
