### ISSUE TITLE
Inpatient/Outpatient bug

### ISSUE THREAD

**Issue by briankip** [ilabafrica/iBLIS#301]
A single visits is not exclusively IP or OP they can be both 

order_date | order_stage | investigation  |
----------------------|-------------|----------------|
| 2015-02-23 11:25:11  | op          | BS for mps     |
| 2015-02-23 11:25:43  | op          | Full Haemogram |
| 2015-02-23 17:45:19  | ip          | Full Haemogram |
| 2015-02-25 11:53:50  | ip          | RFTS           |
| 2015-02-27 11:30:35  | ip          | TFT            |

5 rows in set (0.26 sec)

This means linking the visit type to the visit table is broken, visit type needs to be linked to the test itself, I am not sure if the hospital/HMIS or BLIS is at fault here. 

Since this may require a major change I would like your input. @mapesa @ereng 

A quick fix here is checking the visit type from external_dump.

**Comment by mapesa** [comment]
**My view** is that strictly (logically) speaking op/ip should be pegged to the visit.

I see that the status can change for example if a patient walks in for a routine check-up (op), then after a series of tests or monitoring, the doctor decides to admit him (ip). 

One way around this is to **create another visit at the point where the patient is admitted**.

What changes from an implementation point of view is that now we create a new visit *not only* when the `visit_number` (in `external_dump`) changes *but also* if for the same `visit_number`, the op/ip status changes.
