### ISSUE TITLE
Helpdesk

### ISSUE THREAD

**Issue by briankip** [ilabafrica/iBLIS#324]
Ensure that help-desk sends us mail, when an issue is logged.

**Comment by Piusyo** [comment]
Solved, Working as expected!
1. Instead of php mailer, I used SMTP proctol, created agmail account: Username; `blishelpdesk.ilabafrica@gmail.com`.. password; `blis2500`
2. I had to enabled antispaming for both customers  and staff and also disenabling auto assigning of tickets to staff but every staff will be getting a notifaction as expected when a new issue is launched!

**Comment by ekweyu** [comment]
Add me to the staff receiving the mails
Regards
 On 28 May 2015 11:54, "Piusyo" <notifications@github.com> wrote:

> Solved, Working as expected!
> 1. Instead of php mailer, I used SMTP proctol, created agmail account:
> Username; blishelpdesk.ilabafrica@gmail.com.. password; blis2500
> 2. I had to enabled antispaming for both customers and staff and also
> disenabling auto assigning of tickets to staff but every staff will be
> getting a notifaction as expected when a new issue is launched!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ilabafrica/iBLIS/issues/324#issuecomment-106237211>.
>

-- 


Note: All emails sent from Strathmore University are subject to 
Strathmore’s Email Terms & Conditions. Please click here 
<http://www.strathmore.edu/aboutus.php?id=184> to read the policy.

"Visit our Facebook <https://www.facebook.com/StrathmoreUniversity>Page and Twitter 
<https://twitter.com/StrathU>Account".

**Comment by Piusyo** [comment]
Sure.

**Comment by Piusyo** [comment]
@ekweyu you can login using `administrator`\`password` or `ekweyu`\`password`

**Comment by briankip** [comment]
Change the password for `blishelpdesk.ilabafrica@gmail.com` and share it via email. This is a public website and you should consider that gmail account compromised.
