### ISSUE TITLE
Verification Config

### ISSUE THREAD

**Issue by ereng** [ilabafrica/iBLIS#336]
Allow and disallow sending unverified results to EMR

Restrict allowed sending of unverified results - to certain hours of the day

**Comment by ereng** [comment]
@briankip  what is the difference btn 

`$externalDump->result_returned = 1;` and `$externalDump->result_returned = 2;`
we need to use constants
`$externalDump->result_returned = ExternalDump::WHATEVER;`
`$externalDump->result_returned = ExternalDump::WHENEVER;`
For clarity

**Comment by briankip** [comment]
I think we forgot to put that up. 1 should be  result sent successfully and 2 is result sending failed.

**Comment by ereng** [comment]
Perhaps it must be considered more carefully given comment on

```
/var/www/blis2.5/app/api/SanitasInterfacer.php

23:     //Sending all pending requests also
        $pendingRequests = ExternalDump::where('result_returned', 2)->get();

```

2 represents pending tests also

So I haven't tempered with it yet
