### ISSUE TITLE
QueryException on db:seed

### ISSUE THREAD

**Issue by echiteri** [ilabafrica/iBLIS#359]
I pulled the latest commits on the master branch and I am unable to get past database seeding, hence I am unable to test the new features. I am getting the following errors:

SQLSTATE[42S22]: Column not found: 1054 Unknown column 'number' in 'field list' (SQL: insert into `lots` (`number`, `description  
  `, `expiry`, `instrument_id`, `updated_at`, `created_at`) values (0001, First lot, 2016-10-26 11:18:00, 1, 2016-04-26 11:18:00,   
  2016-04-26 11:18:00)) 

After I manually added the 'number' column, this error springs up:

SQLSTATE[42S22]: Column not found: 1054 Unknown column 'instrument_id' in 'field list' (SQL: insert into `lots` (`number`, `desc  
  ription`, `expiry`, `instrument_id`, `updated_at`, `created_at`) values (0001, First lot, 2016-10-26 11:39:11, 1, 2016-04-26 11:  
  39:11, 2016-04-26 11:39:11)) 

Once again, I manually added the 'instrument_id' column and the following error also springs up:

SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '' for key 'lots_lot_no_unique' (SQL: insert into `lots` (  
  `number`, `description`, `expiry`, `instrument_id`, `updated_at`, `created_at`) values (0002, Second lot, 2016-11-26 14:43:08, 1  
  , 2016-04-26 14:43:08, 2016-04-26 14:43:08))

**Comment by briankip** [comment]
We are looking into this. It seems that seeding is a bit messed up. Thanks for reporting

**Comment by briankip** [comment]
Hi ezekiel this issue is fixed check #360 for more info.
