### ISSUE TITLE
Kapsara instance bug

### ISSUE THREAD

**Issue by echiteri** [ilabafrica/iBLIS#363]
There is an exception error that keeps thrown when a 'test' link is selected on the same instance at Kapsara SCH. I have attached the database backup (patient names masked) and the screenshot of the exception error.
Installed Version: 2.6

![blis_test_error](https://cloud.githubusercontent.com/assets/5479247/15008236/89f92c7e-11e7-11e6-8af1-dfb28749162d.png)
[iblis_kap_masked.sql.gz](https://github.com/ilabafrica/iBLIS/files/248356/iblis_kap_masked.sql.gz)

**Comment by briankip** [comment]
Hi Ezekiel, go to app/storage/logs/laravel.log and post the part of the log with the error here, it's usually more descriptive than the user interface error.

**Comment by echiteri** [comment]
Hi Brian. See the reproduce error logged below:

[2016-05-10 12:11:36] production.ERROR: exception 'ErrorException' with message 'Trying to get property of non-object' in /home/ezekiel/git/iBLIS/app/storage/views/ef3461696516c8acbcafca5ae7604a23:118
Stack trace:
#0 /home/ezekiel/git/iBLIS/app/storage/views/ef3461696516c8acbcafca5ae7604a23(118): Illuminate\Exception\Handler->handleError(8, 'Trying to get p...', '/home/ezekiel/g...', 118, Array)
#1 /home/ezekiel/git/iBLIS/vendor/laravel/framework/src/Illuminate/View/Engines/PhpEngine.php(37): include('/home/ezekiel/g...')
#2 /home/ezekiel/git/iBLIS/vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEngine.php(56): Illuminate\View\Engines\PhpEngine->evaluatePath('/home/ezekiel/g...', Array)
#3 /home/ezekiel/git/iBLIS/vendor/laravel/framework/src/Illuminate/View/View.php(134): Illuminate\View\Engines\CompilerEngine->get('/home/ezekiel/g...', Array)
#4 /home/ezekiel/git/iBLIS/vendor/laravel/framework/src/Illuminate/View/View.php(102): Illuminate\View\View->getContents()
#5 /home/ezekiel/git/iBLIS/vendor/laravel/framework/src/Illuminate/View/View.php(76): Illuminate\View\View->renderContents()
#6 /home/ezekiel/git/iBLIS/vendor/laravel/framework/src/Illuminate/Http/Response.php(43): Illuminate\View\View->render()
#7 /home/ezekiel/git/iBLIS/vendor/symfony/http-foundation/Symfony/Component/HttpFoundation/Response.php(202): Illuminate\Http\Response->setContent(Object(Illuminate\View\View))
#8 /home/ezekiel/git/iBLIS/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1501): Symfony\Component\HttpFoundation\Response->__construct(Object(Illuminate\View\View))
#9 /home/ezekiel/git/iBLIS/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1036): Illuminate\Routing\Router->prepareResponse(Object(Illuminate\Http\Request), Object(Illuminate\View\View))
#10 /home/ezekiel/git/iBLIS/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1001): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#11 /home/ezekiel/git/iBLIS/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(775): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#12 /home/ezekiel/git/iBLIS/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(745): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#13 /home/ezekiel/git/iBLIS/vendor/laravel/framework/src/Illuminate/Session/Middleware.php(72): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#14 /home/ezekiel/git/iBLIS/vendor/laravel/framework/src/Illuminate/Cookie/Queue.php(47): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#15 /home/ezekiel/git/iBLIS/vendor/laravel/framework/src/Illuminate/Cookie/Guard.php(51): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#16 /home/ezekiel/git/iBLIS/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#17 /home/ezekiel/git/iBLIS/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(641): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#18 /home/ezekiel/git/iBLIS/public/index.php(49): Illuminate\Foundation\Application->run()
#19 /home/ezekiel/git/iBLIS/server.php(19): require_once('/home/ezekiel/g...')
#20 {main}

Next exception 'ErrorException' with message 'Trying to get property of non-object (View: /home/ezekiel/git/iBLIS/app/views/test/index.blade.php)' in /home/ezekiel/git/iBLIS/app/storage/views/ef3461696516c8acbcafca5ae7604a23:118
Stack trace:
#0 /home/ezekiel/git/iBLIS/vendor/laravel/framework/src/Illuminate/View/Engines/PhpEngine.php(41): Illuminate\View\Engines\CompilerEngine->handleViewException(Object(ErrorException), 1)
#1 /home/ezekiel/git/iBLIS/vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEngine.php(56): Illuminate\View\Engines\PhpEngine->evaluatePath('/home/ezekiel/g...', Array)
#2 /home/ezekiel/git/iBLIS/vendor/laravel/framework/src/Illuminate/View/View.php(134): Illuminate\View\Engines\CompilerEngine->get('/home/ezekiel/g...', Array)
#3 /home/ezekiel/git/iBLIS/vendor/laravel/framework/src/Illuminate/View/View.php(102): Illuminate\View\View->getContents()
#4 /home/ezekiel/git/iBLIS/vendor/laravel/framework/src/Illuminate/View/View.php(76): Illuminate\View\View->renderContents()
#5 /home/ezekiel/git/iBLIS/vendor/laravel/framework/src/Illuminate/Http/Response.php(43): Illuminate\View\View->render()
#6 /home/ezekiel/git/iBLIS/vendor/symfony/http-foundation/Symfony/Component/HttpFoundation/Response.php(202): Illuminate\Http\Response->setContent(Object(Illuminate\View\View))
#7 /home/ezekiel/git/iBLIS/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1501): Symfony\Component\HttpFoundation\Response->__construct(Object(Illuminate\View\View))
#8 /home/ezekiel/git/iBLIS/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1036): Illuminate\Routing\Router->prepareResponse(Object(Illuminate\Http\Request), Object(Illuminate\View\View))
#9 /home/ezekiel/git/iBLIS/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1001): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#10 /home/ezekiel/git/iBLIS/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(775): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#11 /home/ezekiel/git/iBLIS/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(745): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#12 /home/ezekiel/git/iBLIS/vendor/laravel/framework/src/Illuminate/Session/Middleware.php(72): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#13 /home/ezekiel/git/iBLIS/vendor/laravel/framework/src/Illuminate/Cookie/Queue.php(47): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#14 /home/ezekiel/git/iBLIS/vendor/laravel/framework/src/Illuminate/Cookie/Guard.php(51): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#15 /home/ezekiel/git/iBLIS/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#16 /home/ezekiel/git/iBLIS/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(641): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#17 /home/ezekiel/git/iBLIS/public/index.php(49): Illuminate\Foundation\Application->run()
#18 /home/ezekiel/git/iBLIS/server.php(19): require_once('/home/ezekiel/g...')
#19 {main} [] []

**Comment by briankip** [comment]
Hi Ezekiel first you need to seed the ConfiSettingsSeeder by commenting TestDataSeeder the running `php artisan db:seed`

               // $this->call('KBLISSeeder');
		//$this->call('TestDataSeeder'); <-- comment this and seed 
		$this->call('ConfigSettingSeeder');
		// $this->call('CCCSeeder');


Second it seems that some patients are deleted in your db causing referential integrity issues, run this command in the db to undelete the patients. `update patients set deleted_at == null` 

It should work after that

**Comment by echiteri** [comment]
Hi Brian,

This issue is for the instance: Stable release version 2.6, deployed in the facility. It doesn't have "ConfigSettingSeeder".

Nonetheless, the second option worked. I used "update  patients set deleted_at = NULL where deleted_at is not  NULL;"
