### ISSUE TITLE
Trouble Logging In With the default user:pass provided in instructions

### ISSUE THREAD

**Issue by nafwa03** [ilabafrica/iBLIS#369]
Hi,
I have successfully seeded and installed via composer. I, for the life of me, am not able to login. Any assistance or ideas would be helpful. Is it a token issue perhaps? Thanks in advance.

**Comment by ereng** [comment]
what error is it throwing? on the UI
also check `app/storage/logs/laravel.log`,
(you may want to delete all lines in there first, then try logging in again)
then check for lines like `[2016-04-21 10:21:51] production.ERROR: exception`
you may post it here.

**Comment by nafwa03** [comment]
Hi Ereng,
Thanks for the prompt response. I narrowed it down to an issue with my mod_rewrite settings causing router to fail. No error in the logs, it was just not redirecting properly. Thanks again.

**Comment by briankip** [comment]
@Piusyo can you create a troubleshooting section in the installation instruction [here](https://github.com/ilabafrica/iBLIS/blob/master/README.md) and add that mod_rewrite should be enabled.
