### ISSUE TITLE
stock controller exception

### ISSUE THREAD

**Issue by echiteri** [ilabafrica/iBLIS#378]
The exception is thrown when stock link on breadcrumb after selecting 'add stock' link is selected http://localhost:5000/stock:

[2016-06-22 19:09:32] production.ERROR: exception 'ErrorException' with message 'Missing argument 1 for StockController::index()' in /home/echiteri/git/iBLIS-2.6/app/controllers/StockController.php:10
Stack trace:
#0 /home/echiteri/git/iBLIS-2.6/app/controllers/StockController.php(10): Illuminate\Exception\Handler->handleError(2, 'Missing argumen...', '/home/echiteri/...', 10, Array)
#1 [internal function]: StockController->index()
#2 /home/echiteri/git/iBLIS-2.6/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(231): call_user_func_array(Array, Array)
#3 /home/echiteri/git/iBLIS-2.6/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(93): Illuminate\Routing\Controller->callAction('index', Array)
#4 /home/echiteri/git/iBLIS-2.6/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(62): Illuminate\Routing\ControllerDispatcher->call(Object(StockController), Object(Illuminate\Routing\Route), 'index')
#5 /home/echiteri/git/iBLIS-2.6/vendor/laravel/framework/src/Illuminate/Routing/Router.php(967): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'StockController', 'index')
#6 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#7 /home/echiteri/git/iBLIS-2.6/vendor/laravel/framework/src/Illuminate/Routing/Route.php(109): call_user_func_array(Object(Closure), Array)
#8 /home/echiteri/git/iBLIS-2.6/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1033): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#9 /home/echiteri/git/iBLIS-2.6/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1001): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#10 /home/echiteri/git/iBLIS-2.6/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(775): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#11 /home/echiteri/git/iBLIS-2.6/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(745): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#12 /home/echiteri/git/iBLIS-2.6/vendor/laravel/framework/src/Illuminate/Session/Middleware.php(72): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#13 /home/echiteri/git/iBLIS-2.6/vendor/laravel/framework/src/Illuminate/Cookie/Queue.php(47): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#14 /home/echiteri/git/iBLIS-2.6/vendor/laravel/framework/src/Illuminate/Cookie/Guard.php(51): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#15 /home/echiteri/git/iBLIS-2.6/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#16 /home/echiteri/git/iBLIS-2.6/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(641): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#17 /home/echiteri/git/iBLIS-2.6/public/index.php(49): Illuminate\Foundation\Application->run()
#18 /home/echiteri/git/iBLIS-2.6/server.php(19): require_once('/home/echiteri/...')
#19 {main} [] []

**Comment by briankip** [comment]
@echiteri this has been fixed
