### ISSUE TITLE
Testtype exception

### ISSUE THREAD

**Issue by echiteri** [ilabafrica/iBLIS#379]
Stack trace for exception thrown when 'save' button is selected during testtype configuration without measures.

[2016-06-22 19:16:26] production.ERROR: exception 'ErrorException' with message 'Trying to get property of non-object' in /home/echiteri/git/iBLIS-2.6/app/models/Measure.php:91
Stack trace:
#0 /home/echiteri/git/iBLIS-2.6/app/models/Measure.php(91): Illuminate\Exception\Handler->handleError(8, 'Trying to get p...', '/home/echiteri/...', 91, Array)
#1 /home/echiteri/git/iBLIS-2.6/app/controllers/MeasureController.php(34): Measure->isNumeric()
#2 /home/echiteri/git/iBLIS-2.6/app/controllers/TestTypeController.php(83): MeasureController->store(Array)
#3 [internal function]: TestTypeController->store()
#4 /home/echiteri/git/iBLIS-2.6/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(231): call_user_func_array(Array, Array)
#5 /home/echiteri/git/iBLIS-2.6/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(93): Illuminate\Routing\Controller->callAction('store', Array)
#6 /home/echiteri/git/iBLIS-2.6/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(62): Illuminate\Routing\ControllerDispatcher->call(Object(TestTypeController), Object(Illuminate\Routing\Route), 'store')
#7 /home/echiteri/git/iBLIS-2.6/vendor/laravel/framework/src/Illuminate/Routing/Router.php(967): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'TestTypeControl...', 'store')
#8 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#9 /home/echiteri/git/iBLIS-2.6/vendor/laravel/framework/src/Illuminate/Routing/Route.php(109): call_user_func_array(Object(Closure), Array)
#10 /home/echiteri/git/iBLIS-2.6/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1033): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#11 /home/echiteri/git/iBLIS-2.6/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1001): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#12 /home/echiteri/git/iBLIS-2.6/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(775): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#13 /home/echiteri/git/iBLIS-2.6/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(745): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#14 /home/echiteri/git/iBLIS-2.6/vendor/laravel/framework/src/Illuminate/Session/Middleware.php(72): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#15 /home/echiteri/git/iBLIS-2.6/vendor/laravel/framework/src/Illuminate/Cookie/Queue.php(47): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#16 /home/echiteri/git/iBLIS-2.6/vendor/laravel/framework/src/Illuminate/Cookie/Guard.php(51): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#17 /home/echiteri/git/iBLIS-2.6/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#18 /home/echiteri/git/iBLIS-2.6/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(641): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#19 /home/echiteri/git/iBLIS-2.6/public/index.php(49): Illuminate\Foundation\Application->run()
#20 /home/echiteri/git/iBLIS-2.6/server.php(19): require_once('/home/echiteri/...')
#21 {main} [] []

**Comment by kitsao** [comment]
Fixed.
